apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # these lables are replica set lables
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  replicas: 1
  selector:
  # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: database
      component: mysql
# This is pod definition. pod is subset of replica set
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mysql
    spec:
      serviceAccount: mysql-secret-reader
      initContainers:
      - name: secret-reader
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value \
            --secret-id arn:aws:secretsmanager:us-east-1:315281578625:secret:/roboshop/dev/mysql/root_password-mRS97e \
            --query SecretString --output text | jq -r .MY_SQL_ROOT_PASSWORD > /secrets/mysql-secret-reader.txt
            echo "secret placed successfully"
            cat /secrets/mysql-secret-reader.txt     
      # just for verification
        volumeMounts:
        - name: mysql-secrets
          mountPath: /secrets
      containers:
      - name: mysql
        image: vinod1618/mysql:1.6.0
        volumeMounts:
        - name: mysql-secrets
          mountPath: /secrets
      volumes:
      - name: mysql-secrets
        emptyDir: {}
